<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="FrontMatterTextReader.fs" />
        <Compile Include="SkillFrontMatter.fs" />
        <Compile Include="DomainTypes.fs" />
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="YamlDotNet" Version="17.1.0" />
    </ItemGroup>

</Project>
