<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(NuGetPackageRoot)/fsharp.typeproviders.sdk/8.10.0/src/ProvidedTypes.fsi" />
    <Compile Include="$(NuGetPackageRoot)/fsharp.typeproviders.sdk/8.10.0/src/ProvidedTypes.fs" />
    <Compile Include="..\YamlFrontMatter.TypeProvider\RuntimeHelpers.fs" Link="RuntimeHelpers.fs" />
    <Compile Include="SkillCollectionProvider.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.TypeProviders.SDK" Version="8.10.0">
      <ExcludeAssets>compile;runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YamlFrontMatter\YamlFrontMatter.fsproj" />
  </ItemGroup>

</Project>
